2022-09-06 01:41:34
Available GPU List
id	utilization.gpu(%)	memory.free(MiB)
0 	0                 	32510           
1 	0                 	32510           
2 	0                 	32510           
3 	0                 	32510           
4 	0                 	32510           
5 	0                 	32510           
6 	0                 	32510           
7 	0                 	32510           
Select id #0, 1, 2, 3, 4, 5, 6 for you.
number of parameters :  565319
Let's use 7 GPUs!
number of parameters :  565319
Let's use 7 GPUs!
number of parameters :  565319
Let's use 7 GPUs!
number of parameters :  565319
Let's use 7 GPUs!
number of parameters :  565319
Let's use 7 GPUs!
Number of train data: 310578
Number of val data: 34341
Number of test data: 104206
number of parameters :  565319
Let's use 7 GPUs!
number of parameters :  565319
Let's use 7 GPUs!
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/prefetch_generator/__init__.py", line 80, in run
    for item in self.generator:
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/caoduanhua/score_function/GNN/GNN_graphformer_pyg/graphformer_dataset.py", line 105, in __getitem__
    full_g.ndata['coors'][:ligand_num] += torch.randn(full_g.ndata['coors'][:ligand_num].size(), device=full_g.ndata['coors'].device)#*g.ndata['V']
TypeError: only integer tensors of a single element can be converted to an index

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/prefetch_generator/__init__.py", line 80, in run
    for item in self.generator:
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/caoduanhua/score_function/GNN/GNN_graphformer_pyg/graphformer_dataset.py", line 105, in __getitem__
    full_g.ndata['coors'][:ligand_num] += torch.randn(full_g.ndata['coors'][:ligand_num].size(), device=full_g.ndata['coors'].device)#*g.ndata['V']
TypeError: only integer tensors of a single element can be converted to an index

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/prefetch_generator/__init__.py", line 80, in run
    for item in self.generator:
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/caoduanhua/score_function/GNN/GNN_graphformer_pyg/graphformer_dataset.py", line 105, in __getitem__
    full_g.ndata['coors'][:ligand_num] += torch.randn(full_g.ndata['coors'][:ligand_num].size(), device=full_g.ndata['coors'].device)#*g.ndata['V']
TypeError: only integer tensors of a single element can be converted to an index

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/prefetch_generator/__init__.py", line 80, in run
    for item in self.generator:
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/caoduanhua/score_function/GNN/GNN_graphformer_pyg/graphformer_dataset.py", line 105, in __getitem__
    full_g.ndata['coors'][:ligand_num] += torch.randn(full_g.ndata['coors'][:ligand_num].size(), device=full_g.ndata['coors'].device)#*g.ndata['V']
TypeError: only integer tensors of a single element can be converted to an index

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/prefetch_generator/__init__.py", line 80, in run
    for item in self.generator:
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/caoduanhua/score_function/GNN/GNN_graphformer_pyg/graphformer_dataset.py", line 105, in __getitem__
    full_g.ndata['coors'][:ligand_num] += torch.randn(full_g.ndata['coors'][:ligand_num].size(), device=full_g.ndata['coors'].device)#*g.ndata['V']
TypeError: only integer tensors of a single element can be converted to an index

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/prefetch_generator/__init__.py", line 80, in run
    for item in self.generator:
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/caoduanhua/score_function/GNN/GNN_graphformer_pyg/graphformer_dataset.py", line 105, in __getitem__
    full_g.ndata['coors'][:ligand_num] += torch.randn(full_g.ndata['coors'][:ligand_num].size(), device=full_g.ndata['coors'].device)#*g.ndata['V']
TypeError: only integer tensors of a single element can be converted to an index

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/prefetch_generator/__init__.py", line 80, in run
    for item in self.generator:
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/caoduanhua/score_function/GNN/GNN_graphformer_pyg/graphformer_dataset.py", line 105, in __getitem__
    full_g.ndata['coors'][:ligand_num] += torch.randn(full_g.ndata['coors'][:ligand_num].size(), device=full_g.ndata['coors'].device)#*g.ndata['V']
TypeError: only integer tensors of a single element can be converted to an index

